import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import "../styles/variables.css";
import MainNavigation from "@/components/Header";
import Footer from "@/components/Footer";
import "./not-found";
import ContactModal from "@/components/modals/ContactModal";
import CookiesPopup from "@/common-components/cookies/cookies";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo/logo-4.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MainNavigation />
        {children}
        <Footer />
        <ContactModal />
        <CookiesPopup />
      </body>
    </html>
  );
}
